from pathlib import Path

from setuptools import find_packages, setup

# Rendered as the project description on PyPI (embedded in the wheel/sdist metadata
# at build time — the file itself is not needed at runtime).
_LONG_DESCRIPTION = (Path(__file__).parent / "README.md").read_text(encoding="utf-8")

setup(
    name="secure-ai-pipeline",
    version="3.2.1",
    description="Security for AI-assisted development — AI Agent Blast Radius checkup + code pipeline",
    long_description=_LONG_DESCRIPTION,
    long_description_content_type="text/markdown",
    author="AvinashNutalapati",
    license="MIT",
    url="https://github.com/AvinashNutalapati/secure-ai-pipeline",
    project_urls={
        "Homepage": "https://mirawyn.com",
        "Source": "https://github.com/AvinashNutalapati/secure-ai-pipeline",
        "Issues": "https://github.com/AvinashNutalapati/secure-ai-pipeline/issues",
    },
    keywords=[
        "security", "devsecops", "mcp", "slopsquatting", "supply-chain",
        "sast", "sca", "ai-code-security", "claude", "code-scanning",
    ],
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Topic :: Security",
        "Topic :: Software Development :: Quality Assurance",
        "Environment :: Console",
    ],
    # Only the extensions package ships in the wheel. scripts/ is delivered by the
    # installer/Action; packaging it would drop an orphan `scripts.scanners` (no
    # __init__.py) and squat generic top-level names. The MCP server no longer needs
    # scripts/ — its rules come from the bundled extensions/claude_mcp/_rules_data.py
    # (generated by gen_rules.py), so `pip install secure-ai-pipeline && sap-mcp` works.
    packages=find_packages(include=["extensions", "extensions.*"]),
    python_requires=">=3.10",
    # Core = the stdio MCP server (sap-mcp): the MCP SDK + requests (the package
    # checker). The REST server (sap-rest, the OpenAI GPT Action backend) needs a
    # web stack — opt in with `pip install secure-ai-pipeline[rest]`.
    install_requires=["mcp>=1.2", "requests>=2.31"],
    extras_require={
        "rest": ["fastapi>=0.110", "uvicorn>=0.29", "pydantic>=2.0"],
    },
    entry_points={
        "console_scripts": [
            "sap-mcp=extensions.claude_mcp.mcp_server:main",   # MCP stdio server (Claude Code / Codex / Cursor)
            "sap-rest=extensions.claude_mcp.server:main",       # REST server (OpenAI GPT Action) — needs [rest]
        ]
    },
)
