// Generated by scripts/gen_rules.py from scripts/scanners/sast/ai_insecure_defaults.py — DO NOT EDIT.
export interface GeneratedRule {
  id: string;
  severity: "error" | "warning";
  message: string;
  trigger: string;
  target: string | null;
  flags: string;
  languages: ("python" | "javascript")[];
}

export const GENERATED_RULES: GeneratedRule[] = [
  { id: "tls-verify-false", severity: "error", message: "TLS certificate verification disabled (verify=False) \u2014 allows man-in-the-middle attacks.", trigger: "requests\\.\\w+\\s*\\([^)]*\\bverify\\s*=\\s*False\\b", target: "\\bverify\\s*=\\s*False\\b", flags: "", languages: ["python"] },
  { id: "flask-debug-true", severity: "error", message: "Flask debug=True exposes an interactive debugger that allows arbitrary code execution.", trigger: "app\\.run\\s*\\([^)]*\\bdebug\\s*=\\s*True\\b", target: "\\bdebug\\s*=\\s*True\\b", flags: "", languages: ["python"] },
  { id: "wildcard-cors", severity: "warning", message: "Wildcard CORS (origins=\"*\") lets any website make credentialed requests. Restrict to trusted origins.", trigger: "origins\\s*=\\s*[\\\"']\\*[\\\"']|Access-Control-Allow-Origin[\\\"']?\\s*[:=]\\s*[\\\"']\\*[\\\"']", target: "[\\\"']\\*[\\\"']", flags: "", languages: ["python", "javascript"] },
  { id: "subprocess-shell-true", severity: "error", message: "subprocess with shell=True and user input enables command injection. Pass an argument list instead.", trigger: "subprocess\\.\\w+\\s*\\([^)]*\\bshell\\s*=\\s*True\\b", target: "\\bshell\\s*=\\s*True\\b", flags: "", languages: ["python"] },
  { id: "sql-injection-fstring", severity: "error", message: "SQL query built from an f-string or concatenation \u2014 use parameterised queries (execute(sql, (param,))).", trigger: "\\.execute\\s*\\(\\s*f[\\\"']|\\.execute\\s*\\(\\s*[\\\"'][^\\\"']*[\\\"']\\s*%\\s*\\w|\\.execute\\s*\\(\\s*[\\\"'][^\\\"']*[\\\"']\\s*\\+\\s*\\w", target: null, flags: "", languages: ["python"] },
  { id: "hardcoded-api-key", severity: "error", message: "Hardcoded credential in source. Load it from the environment (os.environ[...]) or a secrets manager.", trigger: "\\b(api_key|secret|password|passwd|token|auth_key|access_key)\\s*=\\s*[\\\"'][^\\\"']{8,}[\\\"']", target: "[\\\"'][^\\\"']{8,}[\\\"']", flags: "i", languages: ["python", "javascript"] },
  { id: "eval-user-input", severity: "error", message: "eval/exec on request data allows arbitrary code execution. Remove it or use a safe parser.", trigger: "\\b(?:eval|exec)\\s*\\(\\s*request\\.", target: null, flags: "", languages: ["python"] },
];
