// Generated by scripts/gen_rules.py from scripts/scanners/sast/ai_insecure_defaults.py — DO NOT EDIT.
export interface GeneratedRule {
  id: string;
  severity: "error" | "warning";
  message: string;
  trigger: string;
  target: string | null;
  flags: string;
  languages: ("python" | "javascript")[];
}

export const GENERATED_RULES: GeneratedRule[] = [
  { id: "tls-verify-false", severity: "error", message: "TLS certificate verification disabled (verify=False) \u2014 allows man-in-the-middle attacks.", trigger: "requests\\.\\w+\\s*\\([^)]*\\bverify\\s*=\\s*False\\b", target: "\\bverify\\s*=\\s*False\\b", flags: "", languages: ["python"] },
  { id: "flask-debug-true", severity: "error", message: "Flask debug=True exposes an interactive debugger that allows arbitrary code execution.", trigger: "app\\.run\\s*\\([^)]*\\bdebug\\s*=\\s*True\\b", target: "\\bdebug\\s*=\\s*True\\b", flags: "", languages: ["python"] },
  { id: "wildcard-cors", severity: "warning", message: "Wildcard CORS (origins=\"*\") lets any website make credentialed requests. Restrict to trusted origins.", trigger: "origins\\s*=\\s*[\\\"']\\*[\\\"']|Access-Control-Allow-Origin[\\\"']?\\s*[:=]\\s*[\\\"']\\*[\\\"']", target: "[\\\"']\\*[\\\"']", flags: "", languages: ["python", "javascript"] },
  { id: "subprocess-shell-true", severity: "error", message: "subprocess with shell=True and user input enables command injection. Pass an argument list instead.", trigger: "subprocess\\.\\w+\\s*\\([^)]*\\bshell\\s*=\\s*True\\b", target: "\\bshell\\s*=\\s*True\\b", flags: "", languages: ["python"] },
  { id: "sql-injection-fstring", severity: "error", message: "SQL query built from an f-string or concatenation \u2014 use parameterised queries (execute(sql, (param,))).", trigger: "\\.execute\\s*\\(\\s*f[\\\"']|\\.execute\\s*\\(\\s*[\\\"'][^\\\"']*[\\\"']\\s*%\\s*\\w|\\.execute\\s*\\(\\s*[\\\"'][^\\\"']*[\\\"']\\s*\\+\\s*\\w", target: null, flags: "", languages: ["python"] },
  { id: "hardcoded-api-key", severity: "error", message: "Hardcoded credential in source. Load it from the environment (os.environ[...]) or a secrets manager.", trigger: "(api_key|secret|password|passwd|token|auth_key|access_key)\\s*=\\s*[\\\"'][^\\\"']{8,}[\\\"']", target: "[\\\"'][^\\\"']{8,}[\\\"']", flags: "i", languages: ["python", "javascript"] },
  { id: "eval-user-input", severity: "error", message: "eval/exec on request data allows arbitrary code execution. Remove it or use a safe parser.", trigger: "\\b(?:eval|exec)\\s*\\(\\s*request\\.", target: null, flags: "", languages: ["python"] },
  { id: "llm-output-to-sink", severity: "error", message: "LLM output flows into a code/command execution sink (eval/exec/shell) \u2014 model output is untrusted; never execute it.", trigger: "(eval|exec|child_process\\.\\w+)\\s*\\([^)]*(completion|llm_response|\\.content|choices\\[0\\]|output_text)", target: null, flags: "i", languages: ["python", "javascript"] },
  { id: "jwt-verify-disabled", severity: "error", message: "JWT signature verification disabled \u2014 tokens can be forged. Verify the signature and pin the algorithm (never 'none').", trigger: "verify_signature[\\x22\\x27]?\\s*[:=]\\s*false|algorithms?\\s*[:=]\\s*\\[\\s*[\\x22\\x27]none", target: null, flags: "i", languages: ["python", "javascript"] },
  { id: "weak-hash", severity: "warning", message: "MD5/SHA-1 are broken for security use (collisions). Use SHA-256+ for integrity/signatures; only keep MD5/SHA-1 for non-security checksums.", trigger: "createHash\\s*\\(\\s*[\\x22\\x27](?:md5|sha1)[\\x22\\x27]", target: null, flags: "i", languages: ["python", "javascript"] },
  { id: "insecure-deserialization", severity: "error", message: "Unsafe deserialization (pickle / yaml.load without SafeLoader) executes arbitrary code on untrusted input.", trigger: "\\b(?:pickle\\.loads?|yaml\\.load)\\s*\\(", target: null, flags: "", languages: ["python"] },
  { id: "insecure-random-token", severity: "warning", message: "The `random` module is not cryptographically secure. Use `secrets` (Python) / crypto.randomBytes (Node) to mint tokens, keys, OTPs, salts.", trigger: "(?:token|secret|password|otp|nonce|salt)[^\\n]{0,40}Math\\.random\\s*\\(|Math\\.random\\s*\\([^\\n]{0,40}(?:token|secret|password|otp|nonce|salt)", target: null, flags: "i", languages: ["python"] },
  { id: "bind-all-interfaces", severity: "warning", message: "Binding to 0.0.0.0 exposes the service on every network interface. Bind to 127.0.0.1 unless external exposure is intended.", trigger: "[\\x22\\x27]0\\.0\\.0\\.0[\\x22\\x27]", target: null, flags: "", languages: ["python"] },
];
