#!/usr/bin/env python3
"""
Generate the cross-language SAST mirrors from the one canonical catalog
(scripts/scanners/sast/ai_insecure_defaults.py):

  - .semgrep/ai-insecure-defaults.yml            (the CI Semgrep ruleset)
  - extensions/vscode/src/rules.generated.ts     (the VS Code rule table)
  - extensions/claude_mcp/_rules_data.py         (bundled rules+CVEs for the MCP/REST server)

Python channels (run_pipeline → npx, the Action, the MCP server) import the
catalog directly; these two files can't (different pattern languages), so they
are generated. Edit a rule in the catalog, then run this.

    python scripts/gen_rules.py            # write the generated files
    python scripts/gen_rules.py --check    # exit 1 if they're stale (CI guard)

stdlib only.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from scanners.sast.ai_insecure_defaults import RULES  # noqa: E402
from scanners.sca.known_cves import KNOWN_CVES  # noqa: E402
from scanners.posture.catalog import POSTURE_RULES  # noqa: E402

SEMGREP_OUT = ROOT / ".semgrep" / "ai-insecure-defaults.yml"
VSCODE_OUT = ROOT / "extensions" / "vscode" / "src" / "rules.generated.ts"
RULES_DATA_OUT = ROOT / "extensions" / "claude_mcp" / "_rules_data.py"

_BANNER = "Generated by scripts/gen_rules.py from scripts/scanners/sast/ai_insecure_defaults.py — DO NOT EDIT."


def _yaml_squote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def _semgrep_patterns(rule) -> str:
    if rule.get("semgrep_raw"):
        return rule["semgrep_raw"].rstrip("\n") + "\n"
    pats = rule["semgrep"]
    if len(pats) == 1:
        return f"    pattern: {_yaml_squote(pats[0])}\n"
    lines = ["    pattern-either:"]
    lines += [f"      - pattern: {_yaml_squote(p)}" for p in pats]
    return "\n".join(lines) + "\n"


def render_semgrep() -> str:
    out = [f"# {_BANNER}", "rules:", ""]
    for r in RULES:
        langs = ", ".join(r["languages"] if "python" in r["languages"] else r["languages"])
        # Semgrep rules here are Python-oriented; emit the python language set.
        sg_langs = "[python]" if "python" in r["languages"] else f"[{langs}]"
        out.append(f"  - id: {r['id']}")
        out.append(_semgrep_patterns(r).rstrip("\n"))
        out.append("    message: >")
        out.append(f"      {r['message']}")
        out.append(f"    languages: {sg_langs}")
        out.append(f"    severity: {r['severity']}")
        out.append("    metadata:")
        out.append("      category: security")
        out.append(f"      cwe: {_yaml_squote(r['cwe'])}")
        out.append("      ai-generated-pattern: true")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def render_vscode() -> str:
    rows = []
    for r in RULES:
        js = r["js"]
        sev = "error" if r["severity"] == "ERROR" else "warning"
        target = json.dumps(js["target"]) if js.get("target") else "null"
        langs = ", ".join(json.dumps(l) for l in r["languages"])
        rows.append(
            f"  {{ id: {json.dumps(r['id'])}, severity: {json.dumps(sev)}, "
            f"message: {json.dumps(r['message'])}, "
            f"trigger: {json.dumps(js['trigger'])}, target: {target}, "
            f"flags: {json.dumps(js.get('flags', ''))}, "
            f"languages: [{langs}] }},"
        )
    return (
        f"// {_BANNER}\n"
        "export interface GeneratedRule {\n"
        "  id: string;\n"
        '  severity: "error" | "warning";\n'
        "  message: string;\n"
        "  trigger: string;\n"
        "  target: string | null;\n"
        "  flags: string;\n"
        '  languages: ("python" | "javascript")[];\n'
        "}\n\n"
        "export const GENERATED_RULES: GeneratedRule[] = [\n"
        + "\n".join(rows)
        + "\n];\n"
    )


def render_rules_data() -> str:
    """A bundled, in-package Python copy of the canonical SAST rules + CVE data, so
    the MCP / REST servers work pip-installed (no dependency on scripts/). repr()
    round-trips faithfully and is deterministic, so --check stays stable."""
    rows = "\n".join(f"    {r!r}," for r in RULES)
    cves = "\n".join(f"    {k!r}: {v!r}," for k, v in KNOWN_CVES.items())
    posture = "\n".join(f"    {r!r}," for r in POSTURE_RULES)
    return (
        '"""\n'
        f"{_BANNER}\n\n"
        "secure-ai-pipeline:rule-source — excluded from the built-in scan.\n\n"
        "Bundled, in-package copy of the canonical SAST rules + offline CVE data +\n"
        "the AI-workflow posture-rule catalog, so the MCP and REST servers\n"
        "(extensions/claude_mcp/rules.py) work when the wheel is pip-installed, with\n"
        "no dependency on the scripts/ tree.\n"
        '"""\n\n'
        f"RULES = [\n{rows}\n]\n\n"
        f"KNOWN_CVES = {{\n{cves}\n}}\n\n"
        f"POSTURE_RULES = [\n{posture}\n]\n"
    )


def main(argv=None) -> int:
    import argparse
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true",
                   help="Exit 1 if the on-disk generated files are stale.")
    args = p.parse_args(argv)

    targets = {SEMGREP_OUT: render_semgrep(), VSCODE_OUT: render_vscode(),
               RULES_DATA_OUT: render_rules_data()}
    stale = []
    for path, content in targets.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path)
            if not args.check:
                path.write_text(content, encoding="utf-8")

    rel = lambda p: p.relative_to(ROOT)
    if args.check:
        if stale:
            print("Stale generated files (run `python scripts/gen_rules.py`):")
            for p in stale:
                print(f"  - {rel(p)}")
            return 1
        print("Generated files are up to date.")
        return 0
    for p in targets:
        print(f"  wrote {rel(p)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
